"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import ssl
from mongoengine import connect
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from the same directory as settings.py
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "-0(#n6!6okfzb@0idv0brjmcrinhq^4h(g-@39=ohkau3j5pe@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

FRONTEND_URL = 'http://localhost:5173'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'mongoengine',
    'corsheaders',
    'Chat',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'
ASGI_APPLICATION = 'mysite.asgi.application'


CHANNEL_LAYERS = {
    'default' : {
        'BACKEND' : 'channels_redis.core.RedisChannelLayer',
        'CONFIG' : {
            'hosts' : [('127.0.0.1',6379)],
        },
    },
}


REST_FRAMEWORK = {
    'DEFULT_AUTHENTICATION_CLASSES' : (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=30),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),         
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'converge.23$S',
        'HOST': 'convergechat.cfwsyokua33d.eu-north-1.rds.amazonaws.com', 
        'PORT': '5432',
    },
    'mongodb':{
        'ENGINE': 'django.db.backends.dummy',
    },
}

# MongoDB configuration
# Support a full MongoDB URI via `MONGO_URI` env var (e.g.
# mongodb://localhost:27017/). If not provided, fall back to host/port.
MONGO_URI = 'mongodb+srv://convergework23_db_user:DRPxZfsnHQRCHQ58@cluster0.s0y3bgk.mongodb.net/'
if MONGO_URI:
    # If a full connection URI is provided, use it.
    connect(db='converge_db', host=MONGO_URI, ssl=True, tlsAllowInvalidCertificates=True)
else:
    # Allow overriding the MongoDB host/port via environment variables.
    # Default to 0.0.0.0 so the server is reachable from the host network
    # when running inside Docker or when binding to all interfaces.
    MONGO_HOST = os.environ.get('MONGO_HOST', '0.0.0.0')
    MONGO_PORT = int(os.environ.get('MONGO_PORT', '27017'))
    connect('converge_db', host=MONGO_HOST, port=MONGO_PORT)

# Use custom authentication backend that talks to MongoDB via mongoengine
AUTHENTICATION_BACKENDS = [
    'api.auth_backend.MongoEngineBackend',
]

# Gmail App Password Configuration
# IMPORTANT: Gmail App Passwords are ALWAYS exactly 16 characters (no spaces)
# Generate one at: https://myaccount.google.com/apppasswords
# Select "Mail" and "Other (Custom name)" -> Enter "Converge App"
APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "your-16-char-app-password-here")  # Set in .env file for security

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_HOST_USER must be set in .env file or as environment variable
# To set it: Create a .env file in backend/remote-work/ with: EMAIL_HOST_USER=your-email@gmail.com
# Or set environment variable: $env:EMAIL_HOST_USER="your-email@gmail.com" (PowerShell)
# IMPORTANT: Replace 'your-email@gmail.com' with the Gmail account that matches APP_PASSWORD
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")  # Empty string if not set
EMAIL_HOST_PASSWORD = APP_PASSWORD
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER if EMAIL_HOST_USER else "noreply@converge.com"

# Debug: Print email configuration (only first 3 chars of password for security)
if DEBUG:
    print(f"[EMAIL CONFIG] User: {EMAIL_HOST_USER}")
    print(f"[EMAIL CONFIG] Password length: {len(APP_PASSWORD.replace(' ', ''))} chars")
    print(f"[EMAIL CONFIG] Password preview: {APP_PASSWORD[:3]}...{APP_PASSWORD[-3:] if len(APP_PASSWORD) > 6 else ''}")
    print(f"[EMAIL CONFIG] .env file path: {env_path}")
    print(f"[EMAIL CONFIG] .env file exists: {env_path.exists()}")

# Validate app password length
if APP_PASSWORD and APP_PASSWORD != "your-16-char-app-password-here" and len(APP_PASSWORD.replace(" ", "")) != 16:
    import warnings
    warnings.warn(
        f"WARNING: APP_PASSWORD should be exactly 16 characters (without spaces). "
        f"Current length: {len(APP_PASSWORD.replace(' ', ''))} characters. "
        f"Gmail authentication may fail. Generate a new app password at: "
        f"https://myaccount.google.com/apppasswords"
    )
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# Email backend configuration is set above (line 164)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create media directories if they don't exist
os.makedirs(MEDIA_ROOT / 'chat_media', exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use signed cookie session engine so Django doesn't attempt to use the
# default database-backed sessions (the default DB is disabled here).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# During local development allow cross-origin requests from any origin so the
# frontend served on different host/port can reach the API. Do NOT use this
# setting in production.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Frontend URL
    'http://127.0.0.1:3000',  # Add this if using 127.0.0.1
    'http://localhost:5173',  # Add this for Vite development server
    'http://localhost:5174'  # Add this for Vite development server (alternative port)
]
# Allow cookies/credentials to be sent cross-site (for session auth if used)
CORS_ALLOW_CREDENTIALS = True

# Trusted origins for CSRF when making POST requests from the frontend development servers
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

