"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import ssl
from mongoengine import connect
from datetime import timedelta
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

FRONTEND_URL = 'http://localhost:5173'

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '93962274226-t1ngpdrcblqqiqmvkpji6eq7h0vvhovl.apps.googleusercontent.com')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'mongoengine',
    'corsheaders',
    'Chat',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'
ASGI_APPLICATION = 'mysite.asgi.application'


CHANNEL_LAYERS = {
    'default' : {
        'BACKEND' : 'channels_redis.core.RedisChannelLayer',
        'CONFIG' : {
            'hosts' : [('127.0.0.1',6379)],
        },
    },
}


REST_FRAMEWORK = {
    'DEFULT_AUTHENTICATION_CLASSES' : (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=30),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),         
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# CORS Configuration - Allow frontend to communicate with backend
CORS_ALLOWED_ORIGINS = [
]

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'converge.23$S',
        'HOST': 'convergechat.cfwsyokua33d.eu-north-1.rds.amazonaws.com', 
        'PORT': '5432',
    },
    'mongodb':{
        'ENGINE': 'django.db.backends.dummy',
    },
}

# MongoDB configuration
# Support a full MongoDB URI via `MONGO_URI` env var (e.g.
# mongodb://localhost:27017/). If not provided, fall back to host/port.
MONGO_URI = os.getenv("MONGO_URI")
if MONGO_URI:
    # If a full connection URI is provided, use it.
    connect(db='converge_db', host=MONGO_URI, ssl=True, tlsAllowInvalidCertificates=True)
else:
    # Allow overriding the MongoDB host/port via environment variables.
    # Default to 0.0.0.0 so the server is reachable from the host network
    # when running inside Docker or when binding to all interfaces.
    MONGO_HOST = os.environ.get('MONGO_HOST', '0.0.0.0')
    MONGO_PORT = int(os.environ.get('MONGO_PORT', '27017'))
    connect('converge_db', host=MONGO_HOST, port=MONGO_PORT)

# Use custom authentication backend that talks to MongoDB via mongoengine
AUTHENTICATION_BACKENDS = [
    'api.auth_backend.MongoEngineBackend',
]

APP_PASSWORD = "mknw oivj issu ecpb"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = APP_PASSWORD
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# Development: print emails to console to avoid SMTP errors locally.
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use signed cookie session engine so Django doesn't attempt to use the
# default database-backed sessions (the default DB is disabled here).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# During local development allow cross-origin requests from any origin so the
# frontend served on different host/port can reach the API. Do NOT use this
# setting in production.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Frontend URL
    'http://127.0.0.1:3000',  # Add this if using 127.0.0.1
    'http://localhost:5173',  # Add this for Vite development server
    'http://localhost:5174'  # Add this for Vite development server (alternative port)
]
# Allow cookies/credentials to be sent cross-site (for session auth if used)
CORS_ALLOW_CREDENTIALS = True

# Trusted origins for CSRF when making POST requests from the frontend development servers
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

